include classpath("application.conf")

node-address {
  protocol = http
  host = elasticmq
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

rest-stats {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}

generate-node-address = false

aws {
  region = elasticmq
  accountId = 000000000000
}

queues {
  sample-queue { }
}

