apiVersion: v1
kind: Secret
metadata:
  name: github-repo-keda-kind
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/<owner>/keda-kind.git
  githubAppID: "<APP_ID>"
  githubAppInstallationID: "<INSTALLATION_ID>"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    <REPLACE_ME>
    -----END RSA PRIVATE KEY-----
