argo-cd:
  fullnameOverride: argocd
  dex:
    enabled: false
  configs:
    params:
      server.insecure: true
      application.namespaces: sample-applicationset
      applicationsetcontroller.namespaces: sample-applicationset
  server:
    service:
      type: ClusterIP
