argo-cd:
  fullnameOverride: argocd
  dex:
    enabled: false
  applicationSet:
    allowAnyNamespace: true
  configs:
    params:
      server.insecure: true
      application.namespaces: sample-applicationset
      applicationsetcontroller.namespaces: sample-applicationset
      applicationsetcontroller.enable.scm.providers: false
  server:
    service:
      type: ClusterIP
