image:
  repository: enqueue
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
queueName: sample-queue
# mode: scheduled
mode: http
sendInterval: 5s
httpPort: 8080
awsEndpoint: http://elasticmq.default.svc.cluster.local:9324
awsRegion: elasticmq
awsAccessKeyID: x
awsSecretAccessKey: x
