image:
  repository: dequeue
  tag: latest
  pullPolicy: IfNotPresent

queueName: sample-queue
queueURL: http://elasticmq.default.svc.cluster.local:9324/queue/sample-queue
queueLength: "1"
awsEndpoint: http://elasticmq.default.svc.cluster.local:9324
awsRegion: elasticmq
awsAccessKeyID: x
awsSecretAccessKey: x
dbConnectionString: postgres://app:app@postgresql.default.svc.cluster.local:5432/app?sslmode=disable
pollingInterval: 5
maxReplicaCount: 5
successfulJobsHistoryLimit: 2
failedJobsHistoryLimit: 2
