apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enqueue.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enqueue.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "enqueue.fullname" . }}
    spec:
      containers:
        - name: enqueue
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
          env:
            - name: AWS_ENDPOINT
              value: {{ .Values.awsEndpoint | quote }}
            - name: AWS_REGION
              value: {{ .Values.awsRegion | quote }}
            - name: QUEUE_NAME
              value: {{ .Values.queueName | quote }}
            - name: ENQUEUE_MODE
              value: {{ .Values.mode | quote }}
            - name: SEND_INTERVAL
              value: {{ .Values.sendInterval | quote }}
            - name: HTTP_PORT
              value: {{ .Values.httpPort | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "enqueue.fullname" . }}-aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "enqueue.fullname" . }}-aws
                  key: AWS_SECRET_ACCESS_KEY
