apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enqueue.fullname" . }}-aws
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | quote }}
