apiVersion: v1
kind: Service
metadata:
  name: {{ include "enqueue.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "enqueue.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.httpPort }}
      targetPort: http
