apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dequeue.fullname" . }}-config
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | quote }}
  DB_CONNECTION_STRING: {{ .Values.dbConnectionString | quote }}
